### ISSUE TITLE
[Administration -> Triggers page] Provide an option to delete a trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#11386]
Often, some triggers are very difficult to troubleshoot and understand, especially triggers where source is not found:
<img width="2542" height="1272" alt="Image" src="https://github.com/user-attachments/assets/237c2ea5-f9a8-421e-920d-ee94cdee1242" />

We should provide a way to Delete/Clear such triggers

this would be more effective than adding extra filters like `missingSource` to just hide those https://github.com/kestra-io/kestra/issues/11230

EDIT: technically easy to do; the impact is that if the flow still exists, it will restart processing as this will be treated as a new save, so the trigger may reappear.

**Comment by hemantmm** [comment]
@anna-geller, can I work on this issue?

**Comment by MilosPaunovic** [comment]
Go for it @hemantmm! 🚀

**Comment by Pradumnasaraf** [comment]
Hey,

The **Delete backfills** option is there now, but it's not deleting the triggers:
https://jam.dev/c/0d7e8cbb-6e27-4485-9341-4992be7533b2

<img width="422" height="105" alt="Image" src="https://github.com/user-attachments/assets/9fd4bdd2-8965-4dd9-8a45-4700c647f6e3" />

**Comment by brian-mulier-p** [comment]
The button is there. However there was an issue on the data we send to the backend so the delete wasn't working properly. My PR above should fix the remaining issues.

**Comment by Pradumnasaraf** [comment]
Hey @brian-mulier-p,
I’m a bit confused, and I am also counting a different error. We now have two options: **Delete Backfills** and **Delete Trigger**. Is that expected, or a mistake?

<img width="1278" height="478" alt="Image" src="https://github.com/user-attachments/assets/202a041f-0de8-47c2-b63a-277a53c4b6bb" />

The **Delete Backfills** option still doesn’t do anything, as I mentioned earlier.

Here’s the error I get when using **Delete Trigger**: https://jam.dev/c/82666b66-d8dc-4b60-a82b-78b1da143fb0

**Comment by brian-mulier-p** [comment]
Yes this is two different buttons and it's expected that they are both there.

The delete backfills is an entirely different concept, it will delete any programmed / expected backfills to occur (for eg. you put a Schedule "* * * * *" with a backfill from 5 min ago you'll expect it to run 5 times to fulfill the schedule slots that were missed in the given timespan, performing a delete backfill will prevent backfill from occuring.

Delete triggers allows to delete the Trigger entity allowing a trigger to work back as-if it was newly created (so if your trigger is stuck for some reason / you want to reset it this is the perfect feature).

However the button should not be red after my changes so you're not under the latest develop version, please update to have the expected behavior.

**Comment by anna-geller** [comment]
@aj-emerich can you make sure the above explanation from Brian about "Delete Trigger" vs "Delete Backfill" behavior for bulk-actions is documented somewhere in our docs? 🙏

**Comment by Pradumnasaraf** [comment]
Got it. It's working now! 

Thank you for the clarification and knowledge, @brian-mulier-p 🙏
