### ISSUE TITLE
[UI] Triggers page shows next execution date inconsistently for Schedule triggers

### ISSUE THREAD

**Issue by sebastianknopf** [kestra-io/kestra#7385]
### Describe the issue

I'm facing some trouble with Schedule triggers in Kestra. My kestra instance (currently v0.19.12) is running as docker container. Everythin works, but the Schedule triggers with cron property do not work.

For testing, I created the following flow:
```yaml
id: vpe_trigger_test
namespace: vpe.test
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
triggers:
  - id: trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"
```

Regarding to the cron expression, I expect the trigger to run the flow once per minute. After saving the flow in the UI and changing to the tab Triggers, I can see the trigger but with wrong execution time:

![Image](https://github.com/user-attachments/assets/899c6402-8a3c-4065-b413-042825cc55c2)

When saving the flow at 15:27, I would expect it to start at 15:28 next time with this cron expression. Sometimes, the next execution timestamp increases in steps of around 10min with every time I refresh the whole page. Sadly, I cannot reproduce this exactly.

However, even if the next exection time is exceeded, I cannot find an additional execution which is triggered by the Schedule trigger.

Any ideas, whats going wrong here?

### Environment

- Kestra Version: 0.19.12

**Comment by anna-geller** [comment]
hmm, I wasn't able to reproduce. Can you try removing the trigger from your code, saving the flow, then re-adding the trigger with a different ID and an explicit cron definition for every minute like so?

```yaml
id: vpe_trigger_test
namespace: vpe.test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
```

btw glad to see you use the German translation 🇩🇪 let me know if you find any translation mistakes

**Comment by sebastianknopf** [comment]
This is pretty interesting... After updating my staging environment to v 0.21.2, everything works like a charm. Your adapted snippet as well as my original snippet.

I'll try to update the production environment tomorrow, then I'll report about what changed.

BTW: The german translation works absolutely fine, especially in v 0.21.2! Thank you for that!

**Comment by anna-geller** [comment]
Great to hear! keep us posted and feel free to close the issue directly if you no longer see any problem here

**Comment by sebastianknopf** [comment]
I updated the production environment to v0.21.2 too, but still facing the issue. After changing the flow to your example, the same behaviour again: Every time I refresh the page, the 'next execution time' is set a few minutes later until a difference from exactly one hour is reached. After reaching this hour, the 'next execution time' is incremented with every minute, but in a difference of one hour.

![Image](https://github.com/user-attachments/assets/c972fb96-9219-4e27-b4ba-781c625f070a)

Could that be, that there's an issue with dayligh saving time between the hosting server and docker here? Maybe also with the MySQL-Server running in background?

Kestra is configured to our German timezone Europe/Berlin in the settings:

![Image](https://github.com/user-attachments/assets/0fb11c50-b49f-4040-ad19-8b076bab9867)

**Comment by sebastianknopf** [comment]
Additionally, I've found another interesting information: The production server is running itself in Europe/Berlin

![Image](https://github.com/user-attachments/assets/00398ce7-8fbe-40c9-9ae6-6feecc02b3c7)

Where as the staging server is running in UTC:

![Image](https://github.com/user-attachments/assets/6969fa4e-0691-4d20-807c-d3560f685cfa)

**Comment by anna-geller** [comment]
ahh I think I know what it is

scheduling is fully decoupled from the UI timezone configured in Settings

so to use the German timezone in scheduling, you would need to explicitly add timezone info, otherwise it will do scheduling in UTC:
```yaml
id: vpe_trigger_test
namespace: vpe.test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
    timezone: Europe/Berlin
```

sorry, I should have mentioned that timezone property sooner

this should resolve the confusion

**Comment by sebastianknopf** [comment]
Sadly, still facing the same issue... After adding the timezone property in the flow, the next exectuion time is shown in German timezone, but still wrong at all. With every refresh of the page, the next execution time is increased:

See following screenshots:

![Image](https://github.com/user-attachments/assets/85db0792-9147-430f-aee3-2be99de0a5c1)

![Image](https://github.com/user-attachments/assets/4723dcab-e1c2-4d94-8131-3afe2ae003b6)

These two screenshots were just a few minutes apart, without changing anything in the flow definition or doing any other action in Kestra. What I noticed is, that the update timestamp also seems to be increased, exactly to the timestamp when I refreshed the page. I could reproduce this behaviour with a third approach at 06:55. Maybe something goes wrong here...?

For the next test, I will set the timezone of the hosting machine back to UTC, as in the staging environment. Maybe there's a problem between `timedatectl` and the Kestra docker container. I'll report as I have changed and tested with that.

**Comment by sebastianknopf** [comment]
After setting the timezone on the hosting machine back to UTC and restarting the kestra docker container, still facing the same issue ...

But until now I found that after chaning the flow definition and then refreshing the Admin > Triggers page, the 'next execution date' is 'running away', when having the 'timezone' property in the flow definition set explicitly). If I remove the 'timezone' property, everything seems to work properly but no executions are listed anyway.

For further debugging, I have reset the flow definition to your inital solution approach (without setting timezone property explicitly). I took a look into the database behind: Directly after updating, I can see the triggers 'next execution date' column is set to the correct next execution date:

![Image](https://github.com/user-attachments/assets/0ea30fb5-719e-4b8d-92d8-53cf84a52d04)

The date is updated after each time the task should have been running. But still no listed executions ...

For further testing, I checked that the MySQL server, Kestra's docker container and and the hosting machine are running in the same timezone. Therefore, I restarted everything, disabled- and re-enabled the trigger in the UI and now it seems to work!

I'd run several tests until tomorrow and then inform you about the results. Idea?

**Comment by anna-geller** [comment]
Love how thorough you approach this! I believe this part is what made the difference:

> I restarted everything, disabled- and re-enabled the trigger in the UI and now it seems to work!

the typical things in the UI — caching, after restarting/reenabling everything is often back to normal so not unusual

**Comment by sebastianknopf** [comment]
Okay, this seems no bug, but a configuration issue on my hosting system. After resetting the timezone information yesterday, everything works. The hosting machine and all related servers (Kestra, MySQL) should run in UTC.

I close this for now, thank you so much for your support!
